spring:
  application:
    name: gulimall-third-party

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tLiZMjEDDQVR4krHEq3
      secret-key: gLw2iW5XgS0VdWXcny3YJrBaydgYvl
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall798

server:
  port: 30000
